exclude_editions:
- LTSC
excluded_actions:
- esol_2024
- esol_2025
kpi_target_date: '2025-10-31'
kpi_target_percentage: 100
migration_categories:
- esol_2024
- esol_2025
target_editions:
- Enterprise
win11_patterns:
- Win11
