- Site Location: Belval
  Site Name: Belval - Luxembourg
  Location: Belval
  Country: Luxembourg
  SDM: Gauthier, Guillaume
- Site Location: Blois
  Site Name: Blois - France
  Location: Blois
  Country: France
  SDM: Gauthier, Guillaume
- Site Location: Bucharest
  Site Name: Bucharest - Romania
  Location: Bucharest
  Country: Romania
  SDM: Cazan, Anca
- Site Location: Buckingham
  Site Name: Hartridge - United Kingdom
  Location: Buckingham
  Country: United Kingdom
  SDM: Proyer, Damon
- Site Location: Cergy
  Site Name: Cergy - France
  Location: Cergy
  Country: France
  SDM: Gauthier, Guillaume
- Site Location: Cinisello
  Site Name: Cinisello - Italy
  Location: Cinisello Balsamo
  Country: Italy
  SDM: Gauthier, Guillaume
- Site Location: Dubai
  Site Name: Dubai - United Arab Emirates
  Location: Dubai
  Country: United Arab Emirates
  SDM: S K, Arif
- Site Location: Duesseldorf
  Site Name: Duesseldorf - Germany
  Location: Dusseldorf
  Country: Germany
  SDM: S K, Arif
- Site Location: Gillingham
  Site Name: Gillingham - United Kingdom
  Location: Gillingham
  Country: United Kingdom
  SDM: Proyer, Damon
- Site Location: Iasi
  Site Name: Iasi - Romania
  Location: Iasi
  Country: Romania
  SDM: Cazan, Anca
- Site Location: Izmir
  Site Name: Izmir - Turkey / ESBAS 2 (PT Phase 1)
  Location: Izmir
  Country: Turkey
  SDM: Cazan, Anca
- Site Location: Krakow
  Site Name: Krakow - Poland
  Location: Krakow
  Country: Poland
  SDM: Wojcik, Rafal
- Site Location: Madrid
  Site Name: Madrid - Spain
  Location: Madrid
  Country: Spain
  SDM: S K, Arif
- Site Location: Rzeszow, Poland
  Site Name: Rzeszow - Poland
  Location: Rzeszow
  Country: Poland
  SDM: Wojcik, Rafal
- Site Location: Stonehouse
  Site Name: Stonehouse - United Kingdom
  Location: Stonehouse
  Country: United Kingdom
  SDM: Proyer, Damon
- Site Location: Technical Center Krakow
  Site Name: Technical Center Krakow
  Location: Krakow
  Country: Poland
  SDM: Wojcik, Rafal
- Site Location: Warsaw
  Site Name: Warsaw - Poland
  Location: Warsaw
  Country: Poland
  SDM: Wojcik, Rafal
- Site Location: Warwick
  Site Name: Warwick - United Kingdom
  Location: Warwick
  Country: United Kingdom
  SDM: Proyer, Damon
- Site Location: Wroclaw
  Site Name: Wroclaw - Poland
  Location: Wroclaw
  Country: Poland
  SDM: Wojcik, Rafal
