milestone_dates:
  kr1_deadline: '2025-06-30'
  kr2_deadline: '2025-10-14'
  kr2_milestone_date: '2025-06-30'
  kr3_deadline: '2025-10-31'
  kr4_deadline: '2025-06-30'
okr_weights:
  kr1_esol_2024: 25
  kr2_esol_2025: 25
  kr3_win11_compatibility: 40
  kr4_kiosk_reprovisioning: 10
status_levels:
  at_risk: 0
  caution: 1
  on_track: 2
status_thresholds:
  caution_min_progress: 60
  on_track_min_progress: 80
targets:
  kr1_target_percentage: 0
  kr2_milestone_percentage: 50
  kr2_target_percentage: 0
  kr3_target_percentage: 90
  kr4_target_count: 0
penalty_thresholds:
  kr1_penalty_threshold_percentage: 1.0
  kr2_penalty_threshold_percentage: 5.0
